name: s3-deploy-sample
on: 
  push:
    branches:
      - main


jobs:
  UploadStaticFiles:
    name: Upload Static Files
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AMIDA_S3_FULL_ACCESS_ROLE_ARN}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ap-northeast-1
      - name: S3 sync 
        working-directory: build
        run: aws s3 sync . s3://amidakuji.kevinbrummer.com --delete